### PR TITLE
Standard Eclipse Tycho folder layout

### PR DESCRIPTION
**Pull request by frankbenoit**
Create a target platform definition
Instead of relying on the running Eclipe IDE of the vrapper developer person, have a defined set of plugins.
With pure PDE, this is done with a .target file which specifies all plugins and their source locations.
Here the tooling is used to specify the needed artifacts with a .tpd file and generate the .launch from it.
See the net.sourceforge.vrapper.target folder

Create the standard folder layout
- features
- plugins - Eclipe plugin projects, not the vrapper "plugins"
- releng - everything that is not real code
- tests

Rename projects
website -> releng/net.sourceforge.vrapper.releng.website
vrapper-stable-update-site -> releng/net.sourceforge.vrapper.releng.update-site
vrapper-unstable-update-site removed
vrapper-stable-feature -> features/net.sourceforge.vrapper.feature

Use qualifier instead of commited timestamps
Eg plugins\net.sourceforge.vrapper.core\META-INF\MANIFEST.MF
Bundle-Version: 0.75.20210730 -> Bundle-Version: 0.75.0.qualifier

Create maven tycho build

Rework bundle dependencies
Before the tests were using specific settings in the .classpath, the manual setup of mockito
and it was using "Eclipse-BuddyPolicy: dependent".
Now the tests are fragments of the plugin under test.
Shared test code is in a new bundle net.sourceforge.vrapper.testutil

### CODE REVIEW

**Comment by frankbenoit** [comment]
in my account I was able to get the build to run: https://github.com/frankbenoit/vrapper/actions

**Comment by albertdev** [comment]
I changed the title, because obviously Eclipse didn't mind the folder layout before and it's chiefly for following Tycho's conventions.

**Comment by keforbes** [comment]
This touched a lot of files, but logically very little changed.  Good work!

**Comment by keforbes** [comment]
> Before the tests were using specific settings in the .classpath, the manual setup of mockito
and it was using "Eclipse-BuddyPolicy: dependent".
Now the tests are fragments of the plugin under test.
Shared test code is in a new bundle net.sourceforge.vrapper.testutil

@frankbenoit I was going to try making a new code change but I can't get the tests to resolve Mockito anymore.  When you said the old way required manual setup of Mockito I thought that meant it was no longer necessary.  How do the tests find Mockito now?

**Comment by albertdev** [comment]
I've got a new laptop and was finally trying out the newest Eclipse. I got it running but I think the developer instructions will need to be completely rewritten.

If you open `releng/net.sourceforge.vrapper.releng.target/net.sourceforge.vrapper.releng.target.target` you will see that Mockito is in there. Eclipse now supports Maven artifacts inside of a target platform definition and behind the scenes it will just turn a random jar into an Eclipse-compatible OSGi bundle.

Make sure your Eclipse is new enough, that the M2E plugin is installed and that you have set this updated target file as the active target platform.

**Comment by keforbes** [comment]
> I think the developer instructions will need to be completely rewritten.

I totally agree.  Hopefully @frankbenoit can help out with that so I don't post the most convoluted way of getting things working. :smile: 

> I used the "Import Maven Project" feature.

That's the trick I needed, thanks!

**Comment by frankbenoit** [comment]
Hi, yes I will help in updating the doc
None of the projects need to be imported as Maven for me. But you need to open the target definition file: /net.sourceforge.vrapper.releng.target/net.sourceforge.vrapper.releng.target.target
Then press in the "Set as active Target Platform"
image
Then all dependencies should be available, including mockito. If there is trouble while loading the target platform, the view "Target Platform State" (open via Ctrl+3) is helpful.

The .target is generated from the .tpd file. 
To make modifikation, the "Target Platform Definition DSL and Generator	3.1.0.202403260932	org.eclipse.cbi.targetplatform.feature.feature.group	Eclipse CBI" should be installed from marketplace.
This is very useful tooling, so you do not fiddle around with every single plugin, but instead you can define features. Also you have autocompletion in the editor and lots of more helpful things.

There is also a .lc file that is used to generate the .launch. Here the "  Launch Configuration DSL	0.5.0.N202402221544	com.wamas.ide.launching.feature.feature.group	SSI Schaefer IT Solutions GmbH" should be installed from market place.
This simplifies configuration of launch configurations, because it automatically drags in the needed depedencies.

**Comment by frankbenoit** [comment]
Shall I support by directly editing the wiki? Or make suggestions here and you take it over?

I propose to get rid of the "how to checkout and import", 
add instructions about minimum Java/Eclipse version and 
the tpd+lc tooling, 
target platform, 
remove point 13+14 about mockito, 
point 16..18 replace with start from the .lc file

**Comment by keforbes** [comment]
> Shall I support by directly editing the wiki? Or make suggestions here and you take it over?

Go ahead and make the change directly.  The old directions are completely wrong now anyway so there's no point in keeping them.

**Comment by keforbes** [comment]
> open the target definition file: /net.sourceforge.vrapper.releng.target/net.sourceforge.vrapper.releng.target.target
Then press the "Set as active Target Platform"

That worked perfectly, thanks!

**Pull request merged**
