### PR TITLE
Vrapper-sneak Mk. II

### PR DESCRIPTION
**Pull request by albertdev**
This has been in progress September 2015 with Mark 1 being implemented in May 2016. I've rewritten it the past few weeks and added to it so that `f`/`F`/`t`/`T` now work as well, giving you a zippy way to navigate your files!

Currently it runs on a cache, doing a search 250 times in a row to find all close occurrences in a single direction. The limit is 500 search items, but it does search for extra items if you use a `count` value before invoking `s`.

To use the plugin, put this in your `.vrapperrc`:

```
nmap s <Plug>(sneak_s)
nmap S <Plug>(sneak_S)

nmap ; <Plug>(sneak-next)
nmap , <Plug>(sneak-prev)

vmap s <Plug>(sneak_s)
vmap Z <Plug>(sneak_S)

vmap ; <Plug>(sneak-next)
vmap , <Plug>(sneak-prev)

nmap f <Plug>(sneak_f)
nmap F <Plug>(sneak_F)
nmap t <Plug>(sneak_t)
nmap T <Plug>(sneak_T)

vmap f <Plug>(sneak_f)
vmap F <Plug>(sneak_F)
vmap t <Plug>(sneak_t)
vmap T <Plug>(sneak_T)

omap z <Plug>(sneak_s)
omap Z <Plug>(sneak_S)
```

I'm still wondering if I can register these mappings by default (at least the `s` and `;` ones) or provide another configuration command.

Suggestions are welcome!

### CODE REVIEW

**Comment by albertdev** [comment]
Paging @mmbradle because I believe he was the first one to propose porting vim-sneak (admittedly back in 2015).

**Comment by keforbes** [comment]
I'll go ahead and merge this in and upload an unstable build so we can test this.  I'll release the next stable version when we're confident with this feature.

**Comment by keforbes** [comment]
Unstable build 0.71.20161019 is ready for testing.

**Comment by loonies** [comment]
Nice. Much easier to move vertically. One thing I have to get used to is
pressing `;` and ',' instead of `n` and `N` to move forward / backward.

**Comment by loonies** [comment]
Vim should have highlighting enabled by default for `f`, `F, `t` and `T`
movements.

**Comment by albertdev** [comment]
I had the chance to use Eclipse at the day job today which caused me to notice sneak being broken at some point.

I'll have to check if I can reproduce it but it had something to do with `s<x><y>`, pressing `;`, `gg` and then `;` a few more times. After a while vrapper-sneak would no longer jump to the next match using `;` though it would highlight all nearby matches.

If others noticed the same problem then I'd still like to hear about it.

**Comment by keforbes** [comment]
Hey @albertdev, I finally released 0.72.0 so I tried writing the documentation for this plugin (http://vrapper.sourceforge.net/documentation/?topic=optional_plugins#sneak).  Did we ever define a custom command to set all the default mappings for this like we did with `:subwordmappings`?

**Comment by albertdev** [comment]
@keforbes, it seems I forgot about that part.

I was originally going to register the sneak shortcuts automatically by implementing something like [Vim's mapcheck](http://vimdoc.sourceforge.net/htmldoc/eval.html#mapcheck%28%29), but I never got a round Tuit.

**Pull request merged**
