### PR TITLE
Update the selection during IncrementalSearch

### LINKED ISSUE #590: Entering search mode from visual mode clears selection, doesn't update with incsearch
As noted in #508, "visual search mode" doesn't keep the selection active. 

Also, when a pattern is entered the incsearch option will now start highlightinh the next match whereas Vim changes the selection to include that match as a way to display the incremental search.

### PR DESCRIPTION
**Pull request by solde9**
I hope I'm not oversimplifying here. I just added a call to `setSelection` inside `doIncSearch`.

Fix #590

### CODE REVIEW

**Comment by keforbes** [comment]
I haven't had a chance to test this myself but from just eyeballing the code, does it handle a reverse search?  Like if you enter search mode with `?` so the match will most likely be above the current selection?  You're using `getStart()` rather than `getLeftBound()` so I think this will work, I just wanted to check with you to see if you already tried this scenario.  I think this code assumes the search is going in the same direction as the current selection (both reversed or both forward) but I'm not sure if that's a problem.

**Comment by solde9** [comment]
@keforbes, thanks for pointing that out because I haven't tested reverse search, so it will be pure luck if it's working now. I will test it later on today.

**Comment by albertdev** [comment]
I played with this for s few moments now thatI got those other issues out of the way.

It doesn't blow up, but it does behave odd: in forward mode the next keyword is highlighted, in backward mode this highlighting is obscured by the selection.

Linewise mode goes slightly wrong if you do a forward search,

**Comment by albertdev** [comment]
Argh, I accidentally closed the PR and lost my message... Curse this mobile layout...

**Comment by albertdev** [comment]
Okay, while I think this pull request is technically incomplete, I do consider merging it when it appears to be stable.

Currently it's hard to do the selection stuff right, the code is spread out over too many places. Having some feedback might still be better than no feedback though, so even simplistic code could be okay in this case.

I guess we can at least keep it open for the time being (accidents excluded).

**Comment by solde9** [comment]
@albertdev thanks for the feedback. I'll see if can find something for the Linewise mode problem

**Comment by solde9** [comment]
It seems I'll also need to ask if I'm actually in VisualMode/LinewiseVisualMode before performing any actions

**Comment by solde9** [comment]
I managed to add the Linewise selection into the equation. I've also added a condition to check if the lastMode is `LinewiseVisualMode` or `VisualMode` before doing anything. What I cannot seem to decipher now is this: when I finish the search in `LinewiseVisualMode` and type `v` to change to `VisualMode`, the start of the selection has been replaced by the start of the Linewise selection. In other words, the original start of selection is lost.

**Comment by solde9** [comment]
Ok I did a little more research on this and it seems it's not actually a problem with my branch because it seems to happen also in `master`. Basically, switching between `VisualMode` and `LinewiseVisualMode` works fine until you enter `SearchMode` being previously in `LinewiseVisualMode`. When you exit `SearchMode`, either by pressing `<CR>` or `<ESC>`, you cannot go back to the original selection in `VisualMode` by pressing `v`. Probably I should create a separate issue for this.

**Comment by albertdev** [comment]
That's likely a bug in the FIX_SELECTION or search motion code where to/from are confused with start/end. I'll take a look at it.

**Comment by solde9** [comment]
I didn't create a new issue since I thought it was very similar to what you describe in #578

**Comment by albertdev** [comment]
@solde9
I got a fix for that issue. I'll commit it tomorrow after I've done some more tests. It might shorten your code a bit.

**Comment by solde9** [comment]
Thanks @albertdev! I noticed that I missed the exclusive/inclusive part so I changed that.

**Comment by keforbes** [comment]
Sorry, I haven't been following this too closely... is this one safe to merge in now or is there more work pending?

**Comment by solde9** [comment]
I couldn't find a solution for the backward highlighting problem. The Linewise selection problem is fixed.

**Comment by albertdev** [comment]
I'll see if I can do something about backward highlighting then and merge this manually.

**Comment by solde9** [comment]
Thanks @albertdev for the help again. I noticed the same thing happening in some visual motions. The highlighting of the previous search is obscured by the selection (given that you have `set hlsearch`). While could be technically the same problem, it would be conceptually different given that in incremental search there is sort of a need of seeing the highlighting appear as you type. In visual motions could not be a problem at all

**Comment by solde9** [comment]
One last tweak: check the `lastModeName` also if search not found.

**Comment by albertdev** [comment]
We're getting awfully close to the release deadline though, so is it OK for you that this will have to wait until after 0.54.0 is released this weekend?

The next unstable build will of course include it.

**Comment by solde9** [comment]
There is no problem at all.

**Comment by albertdev** [comment]
I combined some of your commits and pushed them as e07cea287f and a98b45532b.

In the end I chose to make it more like Vim: there's no longer any `incsearch` highlighting when coming from a visual mode because updating the selection gives sufficient feedback.

I did change your incusive/exclusive code with a call to Selection.reset(), this way it should in theory work with visual block mode whenever we add search to it. The inclusive/exclusive stuff is then handled inside of those method implementations.

Again thanks for the help!

**Comment by solde9** [comment]
That is a lot better! Thanks!

**Pull request closed without merging**
