### PR TITLE
contributing bindingkeeper as an optional plugin

### PR DESCRIPTION
**Pull request by pedrosans**
Hi devs, 

thanks for the Vrapper plugin, it has been of a great help. My only problem is that most of the shortcuts I was used to in VIM were already taken by useless Eclipse's commands like "Print" mapped to "CTRL+P", or really important/usefull shortcuts were important in both Vrapper and Eclipse, so it was a hard to decide between "CTRL+V" fuctions.

My idea is to have the entire 'keys preference' saved and then changed to avoid most of the conflicts with VIM shortcuts when Vrapper is enabled.  This way I can just switch Vrapper on and off and to get the shortcut based on context (VIM's if Vrapper is enabled or Eclipse's if disabled).

I do get that Vrapper is intended to enhance Eclipse's text editor rather than to replace it. But it's my opinion that the keys preference cleanup when Vrapper is enabled, if add as a configurable option, it will benefit developer like me that would rather take the most out of VIM's and Eclipse's shortcuts based on the context (if Vrapper is enabled) rather than try to conciliate both.

I already started a listener that cleans and restores keys preference based on Vrapper state. It's a WIP since it's lacking a preference panel and a better users key bindings restoration logic. But I'm opening the pull request anyway so you can checkout the work can collaborate if it's of interest.

### CODE REVIEW

**Comment by keforbes** [comment]
Cool!  I think this is basically what was requested in #108 so you certainly aren't the only one interested in this behavior.  Although, that issue was filed almost 5 years ago...

**Comment by albertdev** [comment]
Thank you for your interest in Vrapper!

It's somewhat weird though: you're reconfiguring the entire workspace settings to work around a problem in the current editor (or said using Raymond Chen's words, [you are using global state to solve a local problem](https://blogs.msdn.microsoft.com/oldnewthing/20081211-00/?p=19873)). This workaround might leave you stranded in some exotic editor while none of the usual shortcuts work because the life cycle listener might not have fired upon switching editors. I also wonder how we're going to make this intuitive to configure; *personally* I like the default <kbd>CTRL + C</kbd>and <kbd>CTRL + V</kbd> behavior. The user should have some kind of choice, and as far as I know most other Vimulators do (jVi, IDEAVim, VsVim).

Of course, if this WIP fixes your problem then by all means keep using it yourself. Vrapper is a kind of productivity tool, and if your plugin scratches an itch then more power to you!

---

Meanwhile I do have a slight alternative:

Long ago I tried something entirely different in a prototype branch at https://github.com/albertdev/vrapper/tree/EXPERIMENTAL-vrapper-eclipse-keys . This prototype basically implements new Eclipse Command Contexts which allows you to define shortcuts for "Vrapper Normal mode", "Vrapper Insert Mode", ... in the usual Shortcuts editor. No new GUI is needed and the effects should be intuitive (disabling Vrapper should disable those shortcuts).

Sadly the prototype has a flaw: I remember that there was some caching going on where toggling Vrapper would not disable shortcuts, yet reopening the editor or opening a different file would work.

Also, the one thing which makes me doubt the validity of that prototype is that Vrapper does not define the contexts used in e.g. the Java File Editor. It merely defines new ones alongside the actual editor plugins like this:

* Workspace context
** Editing context
*** Java context
** Vrapper dummy context 1
*** Vrapper dummy context 2
**** Vrapper dummy context 3
***** Vrapper Normal mode context

Because the "Vrapper Normal mode" context is at context depth 5 it makes it look as if the Vrapper Contexts are more appropriate than the "Java context" at depth 3. If there is ever an editor plugin which defines as many or more parent contexts, that editor may still override Vrapper.

I hope that gives some background on what I've been trying in the past. If the cache can somehow be disposed, using Eclipse's default key binding switching logic would make the most sense to me as we're actually using the same API's as our target editors would use; letting Eclipse do all the heavy lifting with regards to configuration and the GUI.

Of course, opinions may differ. Sadly the biggest problem is my lack of initiative, I'm coding in C# these days which means I hardly ever open up Eclipse and Vrapper.

**Comment by pedrosans** [comment]
Hi keforbes, nice! haha, 5 years ago I didn't know Vrapper, but am happy to have found it. My first impression was: wow, what a good idea! Then I saw you guys implemented all the important commands really well (congrats!), the only drawback were the conflicting shortcuts.

Hi Bert, amazing trick! I tried the branch here and it successfully intercepted the `CRTL + V` in Eclipse Neon. Hopefully it's just a matter of keep nesting the context if it happens of some other editor get a higher priority. But it failed to work as a regular paste command in any view, even after I disabled Vrapper and restarted the IDE.  I do agree this is a better option than the proposed, but I hope I can find a third one easier to implement. I'm thinking that instead of to remove the conflicting `Binding` objects, to just replace them by emulators that will return the key sequence or command parameter based on the active view.

Anyway the binding manager I proposed is a good easy alternative: it will successfully remove shortcut conflicts, can be easily parametrized and survives Eclipse crashes since it only applies changes in the key mappings after the affected set of mappings got persisted. Besides `CTRL+A CTRL+C CTRL+V CTRL+X CTRL+F CTRL+B`, most of the conflicting shortcuts are barely used by Java developers. For now it's just a matter of to provide a good preference panel in Eclipse's preferences and better default configurations. In a next moment, I will look for better ways of to get this conflict resolution.

I never used an IDE to program in C#, but out of curiosity, isn't Eclipse a good option?

**Comment by pedrosans** [comment]
Hi keforbes, I need a place to explain the plugin and document its update site. As this fork's only goal is to add this plugin I thought it was OK to use the readme file.

Sure, I moved the readme to the "site" branch where I'm keeping the build I'm using.

Let me know if you plan to merge the plugin to Vrapper. I won't have time to implement Bert's solution anytime soon; it will take me some time to get familiar with Eclipse's context management.
 
Also, even though the plugin is almost functional (I'm already using successfully), it's still missing to restore user's key bindings at the right time when users deactivate the editor part; plus it doesn't work for nested editor parts.

**Comment by keforbes** [comment]
Thanks for moving the readme change to another branch.  After we merge in this Pull Request we can update the docs to include a description of the plugin.

I'm fine with merging in this Pull Request once it's ready but I thought you were still working on it.  Like you said, it's still missing some functionality.

**Comment by keforbes** [comment]
Hey @pedrosans, what is the status of this Pull Request?  Is it ready to be merged in?

**Comment by pedrosans** [comment]
Hi @keforbes , there is one pending improvement for this plugin, but at this state I consider it read to be merged since it works fine for non nested AbstractTextEditor parts.

Pending improvement: to detect if the active part is an AbstractTextEditor inside a composite part. Inside Vrapper's code such test is already coded to keep interceptors, inside InputInterceptorManager, and can be refactored to be used by this plugin as well.

**Comment by keforbes** [comment]
Sorry we've been moving so slowly lately.  I finally pulled in #820, which allows you to set all vim/vrapper keys under a `Vim's Key Bindings` Key Scheme which you can toggle on/off.  I'm going to close this pull request in favor of #820.

**Pull request closed without merging**
