### PR TITLE
Line completion fixes

### PR DESCRIPTION
**Pull request by psporysz**
I found some problems and inconsistencies in line completion (**C-x** **C-l**):
* it uses the current editor in opposite to vim and hippie completion (**C-n** / **C-p**) which use all opened buffers
* when search term is narrowed it uses the same list of lines
* cannot go backward which is painful when list is bigger

This pull request is kind of draft how it could be done using existing Eclipse facilities. This way it could be consistent with Hippie completion. If that approach is viable i could make it conform all coding standards and so but first want to know if it will not fail quickly :)

### CODE REVIEW

**Comment by albertdev** [comment]
I'll admit that I never use hippie or line completion, as such I will have to find out what it's all doing first and then try out your code. I take it you want to extend Vrapper's features and implement [Vim's `'complete'` option](http://vimdoc.sourceforge.net/htmldoc/options.html#%27complete%27) at the same time?

One thing that I already noticed is that you changed the platform interfaces. I prefer not to do this often because Vrapper's architecture is supposed to be unaware of real Eclipse features. You also seem to have introduced a new TextContent wrapper copied from ModelTextContent. Is it *really* necessary to have the `HippieCompletionEngine` fetching the list of documents or could we just assume that all opened documents are to be used? If the latter, calling `doInBuffers` on `BufferAndTabService`would work without changing the platform API.

**Comment by psporysz** [comment]
Thanks for response.

I found the current state of line completion in Vrapper not powerful enough for me. Currently i fixed the most limiting things i found. I also miss using contextual complete (**c-x** **c-l** **c-x** **c-l** ...) which provides subsequent lines of text (starting from matched line) but that's the different story :). The whole complete option is definitively a lot of work to do and i do not have so much time. The current strategy in Vrapper is to map the *complete* option directly to Hippie completion. This way Eclipse does the hard work. I do not think it's necessarly wrong since many users are familiar with the algorithm used. That's the reason i exposed it over the API. I can try the *doInBuffers* approach but i guess it require more resources and forces me to reimplement the buffer prioritization part. In spare time i will try to compare the approaches.

**Comment by albertdev** [comment]
I've been doing some more thinking, you're right that `doInBuffers` might not be the right aproach.

My comments on Vrapper platform API changes still stand though so I propose a third solution: moving the `InsertExpandMode` class to the Vrapper-Eclipse project. This way you should be able to get direct access to both Vrapper as well as Eclipse APIs, the only real trouble is getting it hooked up initially. I'll see if I can do just that in a personal branch.

**Comment by albertdev** [comment]
As promised I have played a bit with the code, the result can be found at https://github.com/albertdev/vrapper/tree/EXPERIMENTAL-hippie-line-complete . I've moved the `InsertExpandMode` class to the Eclipse side of the project, granting direct access to the Eclipse APIs. Finally I butchered your patches to work on that base without affecting the platform interfaces.

One thing I did notice though is that `HippieCompletionEngine` is a non-API class. I'm not that happy about that as it may break at some point in the future. Do you know if you have any API you could use instead?

**Comment by psporysz** [comment]
Thanks for help! I think moving that was good idea since Vim's autocomplete requires heavy usage of Eclipse-specific stuff like spellchecking, HippieComplete, autocomplete and probably better UI so it makes the room for improvement in the future.

I will try to find something, but i am worried the only alternative is to rewrite (copy) the current algorithm from Eclipse source code.

**Comment by psporysz** [comment]
Ok, tested it for a few while and it seems to work fine. Since i used only algorithm of document retrieval (sensible order of documents) I copied the method from Eclipse internals, this way we could improve it a bit later and use in own word completion as well.

**Comment by keforbes** [comment]
@albertdev, is this Pull Request ready to be merged?

**Comment by albertdev** [comment]
Sorry about the silence.

I left this pull request without feedback for far too long a time, and I also didn't take the time to verify it whatsoever.

It looks fine at first sight, so it depends if you feel we can take the risk. Either way it only affects `InsertExpandMode`.

**Comment by keforbes** [comment]
If it'll only affect `InsertExpandMode` then we might as well just merge it in.  I don't know how many people use this feature but if it worked for @psporysz then it's unlikely whoever else uses it will run into problems. :smile:

**Comment by psporysz** [comment]
Thanks!

**Pull request merged**
