### PR TITLE
EXPERIMENTAL Blockwise swap

### PR DESCRIPTION
**Pull request by igrekster**
Got the swaps working similar to VIM.
The fake cursor was working fine except on `TAB` characters where it became wide and on empty lines where it becomes thin. A workaround for the wide case could be simply to copy the original with from `caret.getBounds()`.

### CODE REVIEW

**Comment by albertdev** [comment]
I've changed the title to signal that this shouldn't be merged directly because it is built on my experimental code.

I will try your changes and see if I can fix the caret code. Thanks for the help!

**Comment by igrekster** [comment]
Yeah, I figured it wouldn't make much sense for the swap command without the caret visible that's why I put into this branch.

**Comment by igrekster** [comment]
As for the caret width issue, there is also `averageCharWidth` in `EclipseCursorAndSelection`.

**Comment by albertdev** [comment]
I was thinking about this some more, and there's a place where we already do this calculation: `CaretUtils`.

I'm now seriously considering if we shouldn't do away with the whole `EvilCaret` and `CaretType.LEFT_SHIFTED_RECTANGULAR` and simply stick to regular carets. The `PaintListener` from this experiment can move the location of the caret far better because it's also invoked for mouse dragging, and vrapper.core would then no longer need to take care of UI logic.

**Comment by albertdev** [comment]
As for why I've not really worked on this yet: I discovered defect #657 when using this code since the caret painter needs to know the location of the "to" member in a selection. This means I need to fix that problem before completing this feature.

**Comment by albertdev** [comment]
Ok, so that issue I mentioned before got fixed. I have some further changes to allow the caret past the line and to make sure it doesn't change its width, I'll get those checked in tonight.

I have tested your code, but it seems it suffers from the same problem as #661: Vim allows blockwise to move past the last character on the line but Vrapper cuts it off at that last character when you swap the caret between block corners. I'll upload some screenshots to that other issue.

**Comment by igrekster** [comment]
It would seem that even if the right offset is given to `StyledText.getTextBound` it internal `TextLayout` only accounts for the visible characters.

**Comment by albertdev** [comment]
Indeed, it doesn't include the newlines. Maybe we should use getLocationAtOffset(<offset for start of newline>) to see if that Point is actually the edge of the blockwise selection box, and if it is we need to extend the selection an extra "average charwidth" unit to the right.

**Comment by igrekster** [comment]
We could _hack_ it to extend the rectangle by `averageCharWidth` if `to` points past the last visible character, but I imagine it would only work for a fixed width font. A limitation which me might be content with.

**Comment by albertdev** [comment]
I believe enabling blockwise mode changes the font, and normally the user should pick a fixed-width one or face the consequences.

**Comment by igrekster** [comment]
:-) beat me to it.

**Comment by albertdev** [comment]
Right, this can be closed as the rebased version was pushed to master.

**Pull request closed without merging**
