### PR TITLE
Expand Region plugin

### PR DESCRIPTION
**Pull request by psporysz**
Tired of constant pressing 'v' to enter visual mode after selecting enclosing element i wrote the plugin which wraps it. Now it work only in visual mode and can be easily remapped to any comfortable keybinding (personally using `<leader>j` and `<leader>k` for that).

I also experimented with bare `eclipseuiaction` to remap it but unfortunately there is couple of places where Vrapper assumes that exit from command mode should clear the selection (managed though to make it kind of working by commenting out few bits, for details see [this commit](https://github.com/psporysz/vrapper/commit/bfaff2a135af9997784849cdcbb6ee17af3245a9)).

### CODE REVIEW

**Comment by keforbes** [comment]
I don't understand... can you explain this plugin again?  You're performing an eclipse operation to select something in java but Vrapper isn't moving to visual mode so this plugin forces it?

**Comment by psporysz** [comment]
When you try to use "select enclosing element" command, vrapper is not switching to visual mode and in turn after the selection is done, you need to enter the visual mode manually. This introduces unnecessary keystrokes for very frequent operation (i use expand region constantly). Since eclipseuiaction clears the selection (it treats every Eclipse command as Ex command and leaves current command mode to normal mode), you cannot map it like:
```
eclipseuiaction eclipseexpandregion org.eclipse.jdt.ui.edit.text.java.select.enclosing
+vnoremap <Space>j :eclipseexpandregion<cr>v
+nnoremap <Space>j :eclipseexpandregion<cr>v
```
to work-around the mode switch. I tried to change few bits to make it possible but no idea how to fix it in the core without breaking the existing API thus i implemented the mapping in separate plugin.

**Comment by albertdev** [comment]
Thanks for your interest in improving Vrapper!

The thing is that `eclipseaction` and `eclipseuiaction` were never meant for creating a selection, instead their use case is to take a selection (or none at all) and run some Eclipse command from Vrapper. Vrapper then clears the selection to make sure it can safely return to Normal mode.

I can see why you want this though, "Expand Selection To" is also one of my favourite Eclipse features. That's why I've been working on getting some support for Eclipse selection-altering operations where you can use Eclipse's default bindings and still have Vrapper respond to it. While I was far from finished, I can understand that it's intimidating of hacking such a thing into the Vrapper platform/core code.

Meanwhile I think this plugin is only a stopgap as it does override the `+` and `_` keys. For that reason I believe we shouldn't merge your pull request.

As a tradeoff, I might look at my Work In Progress again and see if I can't extract the parts which were already functioning. I believe there was at least something in there to bind Eclipse commands in alternative ways.

**Comment by psporysz** [comment]
I implemented that as a plugin because i share similar thoughts about it and wanted to not "pollute" the core. The bindings could be configured if that's problem (global vars?).

It would be good to be able to declare viml functions which call eclipse commands. Actually i like mapping keys via .vrapperrc since i do not have to import/export the settings every time i setup the environment. So i am looking forward the feature and can help with tests.

**Comment by keforbes** [comment]
Superseded by #762.

**Pull request closed without merging**
