### PR TITLE
EXPERIMENTAL fix the annoying jj-<Esc> bug

### PR DESCRIPTION
**Pull request by idealvin**
A dirty fix for imap jj \<Esc\>. Very useful, though not so elegate.

### CODE REVIEW

**Comment by albertdev** [comment]
Thanks for your work!

I have renamed this pull request though as I'm not so sure that it will be merged as-is. We have had people before who don't use `jj`, so going for a quick shortcut might not be the best way in the long term. Meanwhile I'm also going to reopen your original issue as I'd like to track progress there.

I hope you understand.

**Comment by idealvin** [comment]
@albertdev 
All right. No problem!

**Comment by keforbes** [comment]
Now that #669 has been fixed, can this pull request be closed or is it related to something else?

**Comment by albertdev** [comment]
You're right, this was a workaround until that issue was fixed.
Closed.

**Pull request closed without merging**
